/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 3beb3212c83f633b94886bda44057bbb)
// Runtime types generated with workerd@1.20260820.1 2025-03-10 global_fetch_strictly_public,nodejs_compat
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	GOOGLE_MCP_URL: "https://calendarmcp.googleapis.com/mcp/v1";
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	COOKIE_ENCRYPTION_KEY: string;
	HOSTED_DOMAIN: string;
	GOOGLE_OAUTH_SCOPES: string;
	MCP_OBJECT: DurableObjectNamespace<import("./src/index").MCP_GOOGLE_DB>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MCP_GOOGLE_DB";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}

interface Env {
  MCP_GOOGLE_OAUTH: KVNamespace;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  GOOGLE_OAUTH_SCOPES: string;
  GOOGLE_MCP_URL: string;
  COOKIE_ENCRYPTION_KEY: string;
  HOSTED_DOMAIN: string;
  MCP_OBJECT: DurableObjectNamespace<import("./src/index").MCP_GOOGLE_DB>;
}
